package com.moocollege.dao;

import com.moocollege.dto.QyApp;
import com.moocollege.dto.QyAppCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QyAppMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int countByExample(QyAppCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int deleteByExample(QyAppCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int insert(QyApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int insertSelective(QyApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	List<QyApp> selectByExample(QyAppCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	QyApp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QyApp record, @Param("example") QyAppCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int updateByExample(@Param("record") QyApp record, @Param("example") QyAppCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int updateByPrimaryKeySelective(QyApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	int updateByPrimaryKey(QyApp record);
}