package com.moocollege.dao;

import com.moocollege.dto.QyMenu;
import com.moocollege.dto.QyMenuCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QyMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int countByExample(QyMenuCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int deleteByExample(QyMenuCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int insert(QyMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int insertSelective(QyMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	List<QyMenu> selectByExample(QyMenuCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	QyMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QyMenu record, @Param("example") QyMenuCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int updateByExample(@Param("record") QyMenu record, @Param("example") QyMenuCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int updateByPrimaryKeySelective(QyMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	int updateByPrimaryKey(QyMenu record);
}