package com.moocollege.dto;

import java.util.ArrayList;
import java.util.List;

public class QyAppCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public QyAppCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidIsNull() {
			addCriterion("logo_mediaid is null");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidIsNotNull() {
			addCriterion("logo_mediaid is not null");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidEqualTo(String value) {
			addCriterion("logo_mediaid =", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidNotEqualTo(String value) {
			addCriterion("logo_mediaid <>", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidGreaterThan(String value) {
			addCriterion("logo_mediaid >", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidGreaterThanOrEqualTo(String value) {
			addCriterion("logo_mediaid >=", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidLessThan(String value) {
			addCriterion("logo_mediaid <", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidLessThanOrEqualTo(String value) {
			addCriterion("logo_mediaid <=", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidLike(String value) {
			addCriterion("logo_mediaid like", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidNotLike(String value) {
			addCriterion("logo_mediaid not like", value, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidIn(List<String> values) {
			addCriterion("logo_mediaid in", values, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidNotIn(List<String> values) {
			addCriterion("logo_mediaid not in", values, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidBetween(String value1, String value2) {
			addCriterion("logo_mediaid between", value1, value2, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andLogoMediaidNotBetween(String value1, String value2) {
			addCriterion("logo_mediaid not between", value1, value2, "logoMediaid");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNull() {
			addCriterion("agent_id is null");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNotNull() {
			addCriterion("agent_id is not null");
			return (Criteria) this;
		}

		public Criteria andAgentIdEqualTo(Integer value) {
			addCriterion("agent_id =", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotEqualTo(Integer value) {
			addCriterion("agent_id <>", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThan(Integer value) {
			addCriterion("agent_id >", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("agent_id >=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThan(Integer value) {
			addCriterion("agent_id <", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThanOrEqualTo(Integer value) {
			addCriterion("agent_id <=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdIn(List<Integer> values) {
			addCriterion("agent_id in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotIn(List<Integer> values) {
			addCriterion("agent_id not in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdBetween(Integer value1, Integer value2) {
			addCriterion("agent_id between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("agent_id not between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainIsNull() {
			addCriterion("redirect_domain is null");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainIsNotNull() {
			addCriterion("redirect_domain is not null");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainEqualTo(String value) {
			addCriterion("redirect_domain =", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainNotEqualTo(String value) {
			addCriterion("redirect_domain <>", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainGreaterThan(String value) {
			addCriterion("redirect_domain >", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainGreaterThanOrEqualTo(String value) {
			addCriterion("redirect_domain >=", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainLessThan(String value) {
			addCriterion("redirect_domain <", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainLessThanOrEqualTo(String value) {
			addCriterion("redirect_domain <=", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainLike(String value) {
			addCriterion("redirect_domain like", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainNotLike(String value) {
			addCriterion("redirect_domain not like", value, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainIn(List<String> values) {
			addCriterion("redirect_domain in", values, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainNotIn(List<String> values) {
			addCriterion("redirect_domain not in", values, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainBetween(String value1, String value2) {
			addCriterion("redirect_domain between", value1, value2, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andRedirectDomainNotBetween(String value1, String value2) {
			addCriterion("redirect_domain not between", value1, value2, "redirectDomain");
			return (Criteria) this;
		}

		public Criteria andIsreportuserIsNull() {
			addCriterion("isreportuser is null");
			return (Criteria) this;
		}

		public Criteria andIsreportuserIsNotNull() {
			addCriterion("isreportuser is not null");
			return (Criteria) this;
		}

		public Criteria andIsreportuserEqualTo(Integer value) {
			addCriterion("isreportuser =", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserNotEqualTo(Integer value) {
			addCriterion("isreportuser <>", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserGreaterThan(Integer value) {
			addCriterion("isreportuser >", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserGreaterThanOrEqualTo(Integer value) {
			addCriterion("isreportuser >=", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserLessThan(Integer value) {
			addCriterion("isreportuser <", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserLessThanOrEqualTo(Integer value) {
			addCriterion("isreportuser <=", value, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserIn(List<Integer> values) {
			addCriterion("isreportuser in", values, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserNotIn(List<Integer> values) {
			addCriterion("isreportuser not in", values, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserBetween(Integer value1, Integer value2) {
			addCriterion("isreportuser between", value1, value2, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportuserNotBetween(Integer value1, Integer value2) {
			addCriterion("isreportuser not between", value1, value2, "isreportuser");
			return (Criteria) this;
		}

		public Criteria andIsreportenterIsNull() {
			addCriterion("isreportenter is null");
			return (Criteria) this;
		}

		public Criteria andIsreportenterIsNotNull() {
			addCriterion("isreportenter is not null");
			return (Criteria) this;
		}

		public Criteria andIsreportenterEqualTo(Integer value) {
			addCriterion("isreportenter =", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterNotEqualTo(Integer value) {
			addCriterion("isreportenter <>", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterGreaterThan(Integer value) {
			addCriterion("isreportenter >", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterGreaterThanOrEqualTo(Integer value) {
			addCriterion("isreportenter >=", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterLessThan(Integer value) {
			addCriterion("isreportenter <", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterLessThanOrEqualTo(Integer value) {
			addCriterion("isreportenter <=", value, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterIn(List<Integer> values) {
			addCriterion("isreportenter in", values, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterNotIn(List<Integer> values) {
			addCriterion("isreportenter not in", values, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterBetween(Integer value1, Integer value2) {
			addCriterion("isreportenter between", value1, value2, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andIsreportenterNotBetween(Integer value1, Integer value2) {
			addCriterion("isreportenter not between", value1, value2, "isreportenter");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNull() {
			addCriterion("home_url is null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNotNull() {
			addCriterion("home_url is not null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlEqualTo(String value) {
			addCriterion("home_url =", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotEqualTo(String value) {
			addCriterion("home_url <>", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThan(String value) {
			addCriterion("home_url >", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThanOrEqualTo(String value) {
			addCriterion("home_url >=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThan(String value) {
			addCriterion("home_url <", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThanOrEqualTo(String value) {
			addCriterion("home_url <=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLike(String value) {
			addCriterion("home_url like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotLike(String value) {
			addCriterion("home_url not like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIn(List<String> values) {
			addCriterion("home_url in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotIn(List<String> values) {
			addCriterion("home_url not in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlBetween(String value1, String value2) {
			addCriterion("home_url between", value1, value2, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotBetween(String value1, String value2) {
			addCriterion("home_url not between", value1, value2, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagIsNull() {
			addCriterion("report_location_flag is null");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagIsNotNull() {
			addCriterion("report_location_flag is not null");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagEqualTo(Integer value) {
			addCriterion("report_location_flag =", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagNotEqualTo(Integer value) {
			addCriterion("report_location_flag <>", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagGreaterThan(Integer value) {
			addCriterion("report_location_flag >", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("report_location_flag >=", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagLessThan(Integer value) {
			addCriterion("report_location_flag <", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagLessThanOrEqualTo(Integer value) {
			addCriterion("report_location_flag <=", value, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagIn(List<Integer> values) {
			addCriterion("report_location_flag in", values, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagNotIn(List<Integer> values) {
			addCriterion("report_location_flag not in", values, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagBetween(Integer value1, Integer value2) {
			addCriterion("report_location_flag between", value1, value2, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andReportLocationFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("report_location_flag not between", value1, value2, "reportLocationFlag");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andTokenIsNull() {
			addCriterion("token is null");
			return (Criteria) this;
		}

		public Criteria andTokenIsNotNull() {
			addCriterion("token is not null");
			return (Criteria) this;
		}

		public Criteria andTokenEqualTo(String value) {
			addCriterion("token =", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotEqualTo(String value) {
			addCriterion("token <>", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThan(String value) {
			addCriterion("token >", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThanOrEqualTo(String value) {
			addCriterion("token >=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThan(String value) {
			addCriterion("token <", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThanOrEqualTo(String value) {
			addCriterion("token <=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLike(String value) {
			addCriterion("token like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotLike(String value) {
			addCriterion("token not like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenIn(List<String> values) {
			addCriterion("token in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotIn(List<String> values) {
			addCriterion("token not in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenBetween(String value1, String value2) {
			addCriterion("token between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotBetween(String value1, String value2) {
			addCriterion("token not between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andAesKeyIsNull() {
			addCriterion("aes_key is null");
			return (Criteria) this;
		}

		public Criteria andAesKeyIsNotNull() {
			addCriterion("aes_key is not null");
			return (Criteria) this;
		}

		public Criteria andAesKeyEqualTo(String value) {
			addCriterion("aes_key =", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyNotEqualTo(String value) {
			addCriterion("aes_key <>", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyGreaterThan(String value) {
			addCriterion("aes_key >", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyGreaterThanOrEqualTo(String value) {
			addCriterion("aes_key >=", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyLessThan(String value) {
			addCriterion("aes_key <", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyLessThanOrEqualTo(String value) {
			addCriterion("aes_key <=", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyLike(String value) {
			addCriterion("aes_key like", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyNotLike(String value) {
			addCriterion("aes_key not like", value, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyIn(List<String> values) {
			addCriterion("aes_key in", values, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyNotIn(List<String> values) {
			addCriterion("aes_key not in", values, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyBetween(String value1, String value2) {
			addCriterion("aes_key between", value1, value2, "aesKey");
			return (Criteria) this;
		}

		public Criteria andAesKeyNotBetween(String value1, String value2) {
			addCriterion("aes_key not between", value1, value2, "aesKey");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qy_app
	 * @mbggenerated  Fri Apr 29 10:38:08 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qy_app
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 28 15:20:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}