package com.moocollege.dto;

import java.io.Serializable;

public class QyMenu implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.app_id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.name
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.keywords
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private String keywords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.type
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qy_menu.url
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qy_menu
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.id
	 * @return  the value of qy_menu.id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.id
	 * @param id  the value for qy_menu.id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.app_id
	 * @return  the value of qy_menu.app_id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.app_id
	 * @param appId  the value for qy_menu.app_id
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.name
	 * @return  the value of qy_menu.name
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.name
	 * @param name  the value for qy_menu.name
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.keywords
	 * @return  the value of qy_menu.keywords
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.keywords
	 * @param keywords  the value for qy_menu.keywords
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords == null ? null : keywords.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.type
	 * @return  the value of qy_menu.type
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.type
	 * @param type  the value for qy_menu.type
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qy_menu.url
	 * @return  the value of qy_menu.url
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qy_menu.url
	 * @param url  the value for qy_menu.url
	 * @mbggenerated  Sat Apr 30 00:33:20 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}